### PR TITLE
Version Manager fixes

### LINKED ISSUE #172: [APP BUG]: Check for Pre-release Updates
### Checklist

- [x] I have searched for a similar issue in this repository and did not find one.
- [x] I am using an official build obtained from [releases](https://github.com/shadps4-emu/shadPS4/releases) or updated one of those builds using its in-app updater.

### Describe the Bug

Notice: I had to delete folders `shadPS4` and `shadPS4QtLauncher` in path `\AppData\Roaming` to see if the error was still present.

There's an error checking for pre-release updates. The emulator version downloads but isn't displayed. If you check again, a message appears indicating you already have the pre-release version installed, even though it's not listed.

### Reproduction Steps

Image

Essentially, I simulated the first clean launch of the application, then clicked the button in the picture above. I was prompted to update. I selected Yes, and saw the following message in the terminal:

Image

### Expected Behavior

The update should be error-free.

### Specify OS Version

Windows 11

### CPU

Intel Core i5-8600k

### GPU

RTX 3070

### Amount of RAM in GB

32 GB

### PR DESCRIPTION
**Pull request by DanielSvoboda**
When downloading a version, the system now checks if a version with the same name already exists and deletes the old one to avoid duplicate entries.

Prevented the creation of local folders named "Pre-release" or "Pre-release-shadPS4".

**Code Name**
- Pre-release versions now receive the first 7 characters of the hash as their code name.
- Local versions now always receive the code name "Local".

**Date Format**
- Standardized all displayed dates to the format yyyy-MM-dd (e.g. 2025-10-31).

**Deletion Logic**
- Reintroduced folder deletion functionality, except for local builds.

**Ordering**
- The list of installed versions is now correctly ordered as follows: Pre-release, release, custom.
- If there are any items in the list, 'None' will not appear; it only appears if the list is empty.

**Bug Fixes**
- Fixed an issue where downloading a version would start twice after refreshing the download list.

**Issue 172**
- It also corrects [Issue 172](https://github.com/shadps4-emu/shadps4-qtlauncher/issues/172), where clicking on 'Check for Pre-release Updates' and the user did not have a pre-release downloaded, it was not indexed correctly.

**Extra**
- Removed unnecessary translations for 1.0,  2.0,  3.0

image
image

### CODE REVIEW

**Comment by kalaposfos13** [comment]
Actually, since we don't need to encode information into folder names anymore, can't we also simplify the logic for that too? Also, I'm not sure if a popup is needed for informing the user that for a local build, only the reference is deleted, not the file, or at least not every time.

File: src/qt_gui/main_window.cpp [hunk 1]
```diff
@@ -1426,25 +1426,72 @@ void MainWindow::RestartEmulator() {
...
 void MainWindow::LoadVersionComboBox() {
     ui->versionComboBox->clear();
-    ui->versionComboBox->addItem(tr("None"));
-    ui->versionComboBox->setCurrentIndex(0);
     ui->versionComboBox->setSizeAdjustPolicy(QComboBox::AdjustToContents);
 
     QString savedVersionPath = m_gui_settings->GetValue(gui::vm_versionSelected).toString();
+    auto versions = VersionManager::GetVersionList();
+
+    std::sort(versions.begin(), versions.end(), [](const auto& a, const auto& b) {
```
Comment (kalaposfos13) [inline src/qt_gui/main_window.cpp:1434]: This could be optionally refactored to work with std::tuple-s instead, but this version also works fine.

**Comment by GHU7924** [comment]
>Deletion Logic
Reintroduced folder deletion functionality, except for local builds.


So, does this mean that local builds aren't copied to the versions folder, but are launched from the original path? (When adding a local build, I didn't find a copy in the versions folder)

2) When I click the "Check for Pre-release Updates" button, two windows appear in sequence, which I think is incorrect:

изображение

I think it should be taken into account whether the user has a pre-release version installed, so that one message appears in one case and another in the other. I think in the second case there should be a different message, something like: A new pre-release version has been detected. Would you like to update to the new version?

3) If you have a pre-release version installed, the updater window (where the changelog is) will display the current and new pre-release versions, but these lines are missing dates. So, it's clear that I'm updating to a new version, but then I don't know how much time has passed between updates.

4) This PR also partially solves problem #170. There are only two remaining questions: the ability to add PR/Branch information and implement your idea if it's approved. Regarding the build updates, I admit I miscalculated, so we'll ignore that part.

P.S. The only other thing I'd like to see, if you approve (or at least give me your opinion), is to add a "Release Date" column to the download list, and also include the install date in the installed versions list (perhaps separated by a slash, something like Date/Installation Date).

изображение

I don't know if I missed something or not, but I hope that someone else will also test this PR.

**Comment by Silver-Skyy** [comment]
just wanted to add that it fixes this issue as well ( #159 )

**Comment by DanielSvoboda** [comment]
@GHU7924 
1. Yes, local builds don't create copies, only a reference to the original location.
For example, if I compile a version on my PC, I can add it, so that whenever I change the executable, it will be loaded in the folder I selected.

image



2. The correct way to download would be by selecting the pre-release version from the list on the right, but if you click to update and don't have it downloaded, this message will appear. The second message appears because the item is automatically added to the list as if you had clicked on it, and it's normal for this message to appear. 
Perhaps removing the first message and leaving only the second one would be a good idea.

3. Yes, it would be good to include the dates on the update screen, where the changelog appears, similar to the interface updater.

4. In this PR, I will not include PR/branch information.

Unfortunately, the source of the information on the number of available releases doesn't include the date; I would have to make more requests to retrieve this information. and I prefer to make as few requests as possible.
image

**Comment by GHU7924** [comment]
@DanielSvoboda 

1 and 3 👍  

2 Honestly, I don't even know which is better...

4 Okay.

5 I think you're right, it would be better if there were fewer requests, so okay.
